/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tdd.intro.jbrains

import kotlin.test.Test
import kotlin.test.assertTrue

class AppTest {
    @Test
    fun test() {
        assertTrue { false }
    }
}
